name: Trigger Readme Rebuild

on:
  push:
    paths:
      - meta/**
  workflow_dispatch:

jobs:
  TriggerReadmeRebuild:
    uses:
      NightmareXIV/MyDalamudPlugins/.github/workflows/Create_readme_full.yml@main
    secrets: inherit